# =================================================================================
# Site Configuration
# =================================================================================

title               :   blank                           # The site title (if blank, full name will be used instead)
full_name           :   Your Full Name                  # The full site name (if blank, title will be used instead)
email               :   'your@gmail.com'                # Your email address
lang                :   en                              # Site language (en for English)
encoding            :   utf-8                           # Site encoding (utf-8 for Unicode)
icon                :   '/assets/favicon/favicon.ico'   # Site favicon
logo                :   '/assets/logo/logo.jpg'         # Site logo, also used in jekyll-seo-tag
home-bg             :   '/assets/images/home-bg.jpg'    # Home background image
url                 :   'https://inkstream.netlify.app' # Site URL (if using a custom domain)
baseurl             :   ''                              # Site base URL (add if site is not at root)
repo                :   'https://github.com/dev-mdirfan/inkstream' # Site repository, also used in jekyll-seo-tag
description         :   > # Site description and default description, also used in jekyll-seo-tag
    A minimal, responsive, and fast Jekyll theme for personal blogs and portfolios.
keywords            :   > # For SEO
    jekyll, theme, minimal, responsive, blog, portfolio, fast, seo, social, web, development
footer_text         :   '© 2021 Inkstream'  # Footer text



# =================================================================================
# Theme Settings
# =================================================================================

# ---




# =================================================================================
# Social Integration
# =================================================================================

social_links: # Leave blank according to your need
    linkedin_username       :   mdirfan57               # Your LinkedIn username
    github_username         :   dev-mdirfan             # Your GitHub username
    twitter_username        :   mohdirfan57             # Your Twitter username
    stackoveflow_username   :   13520260/mohd-irfan     # Your Stackoverflow username
    codepen_username        :   mohdirfan57             # Your Codepen username

user:
    name        :   Sarah Parker                # Your name (required)
    bio         :   'A passionate web developer and designer.'    # Short bio, You can also provide a links.
    profession  :   'Web Developer'             # Your profession (optional)
    location    :   'India'                     # Your location (optional)
    email       :   your@gmail.com              # Your email address (optional)

download_resume: '/assets/resume/resume.pdf'    # Add the path to your resume



# =================================================================================
# Jekyll Settings
# =================================================================================

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter_opts:
        css_class: "highlight"
        span:
            line_numbers: false
        block:
            line_numbers: false
            start_line: 1

# Includes & excludes
include: ["_pages", "blog", "_posts"]
exclude:
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - inkstream.gemspec
    - .jekyll-cache
    - /demo/
    # - CONTRIBUTING.md
    # - INSTALL.md

# Plugins
plugins:
    - jekyll-paginate
    - jekyll-seo-tag

# Defaults
defaults:
    - # Page settings
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
    - # Post settings
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: ""
        values:
            image: '/assets/images/posts/default-post-img.jpg' # Default post image
    # - # Sitemap settings
    #     scope:
    #         path: "assets"
    #     values:
    #         sitemap: false



# =================================================================================
# Site Navigation
# =================================================================================

# Nav Links
navigation_header:
    -
        title: Home
        url: /
        icon: home
    -
        title: Blog
        url: /blog/
        icon: blog
    -
        title: About Me
        url: /about/
        icon: user

navigation_footer:
    -
        title: Mohd Irfan
        url: https://github.com/dev-mdirfan/

# Gem settings (jekyll-paginate, jekyll-seo-tag)
paginate            : 5         # jekyll-paginate > items per page
paginate_path       : blog/:num # jekyll-paginate > blog page
pinned              : false     # jekyll-seo-tag > pin the post to the top of the list
author              : MohdIrfan # jekyll-seo-tag > default author
twitter:
    username: mohdirfan57 # jekyll-seo-tag > Owners twitter username
social: # jekyll-seo-tag > social overrides
    name: Mohd Irfan # jekyll-seo-tag > real name
    links: # jekyll-seo-tag > social aliases (sameAs)
        - https://twitter.com/mohdirfan57 # Add your Twitter URL
        - https://www.linkedin.com/in/mdirfan57 # Add your LinkedIn URL
        - https://github.com/dev-mdirfan # Add your GitHub URL

# 4. Jekyll settings
# sass:
#     style: compressed # Style compression
# permalink: pretty # Permalink style (/YYYY/MM/DD/page-name/)
# excerpt_separator: <!-- more --> # Marks end of excerpt in posts
# timezone: Europe/London # Timezone for blog posts and alike

# 5. Jekyll collections settings
collections:
    posts:
        title: Posts # Needed for Siteleaf
        output: true
        description: 'My thoughts and ideas' # The post list page content
        pin: true # Pin the post to the top of the list
        image: 'https://picsum.photos/2560/600?image=866'

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
    '16': '/assets/favicon/favicon-16x16.png'
    '32': '/assets/favicon/favicon-32x32.png'
    '150': '/assets/favicon/mstile-150x150.png'
    '180': '/assets/favicon/apple-touch-icon.png'
    '192': '/assets/favicon/android-chrome-192x192.png'
    '512': '/assets/favicon/android-chrome-512x512.png'
    webmanifest: '/assets/favicon/site.webmanifest'
    safari: '/assets/favicon/safari-pinned-tab.svg'


#     Email: true

# # Load custom fonts from fonts.google.com etc
# #
# # TIP: Try to keep the number of urls as low to reduce the performance cost
# #      If multiple fonts can be requested in a single url opt for this
# fonts:
#     preconnect_urls:
#         - https://fonts.gstatic.com
#     font_urls:
#         - https://use.fontawesome.com/releases/v5.7.1/js/all.js
